// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VkrItDbContext))]
    [Migration("20251228234017_MainSchemReady")]
    partial class MainSchemReady
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Action", b =>
                {
                    b.Property<long>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ActionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ActionId")
                        .HasName("pk_action");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_action_code");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ActionParamRequirement", b =>
                {
                    b.Property<long>("ActionVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_version_id");

                    b.Property<long>("ParamDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("param_definition_id");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("UiPrompt")
                        .HasColumnType("text")
                        .HasColumnName("ui_prompt");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_kind");

                    b.HasKey("ActionVersionId", "ParamDefinitionId")
                        .HasName("pk_action_param_requirement");

                    b.HasIndex("ParamDefinitionId")
                        .HasDatabaseName("ix_action_param_requirement_param_definition_id");

                    b.HasIndex("ActionVersionId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_action_param_requirement_sort_order");

                    b.ToTable("action_param_requirement", null, t =>
                        {
                            t.HasCheckConstraint("ck_action_param_requirement_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_action_param_requirement_value_kind", "value_kind IN ('CONSTANT','VARIABLE')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ActionVersion", b =>
                {
                    b.Property<long>("ActionVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("action_version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ActionVersionId"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("released_at");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_label");

                    b.HasKey("ActionVersionId")
                        .HasName("pk_action_version");

                    b.HasIndex("ActionId")
                        .IsUnique()
                        .HasDatabaseName("uq_action_version_action_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("ActionId", "VersionLabel")
                        .IsUnique()
                        .HasDatabaseName("uq_action_version_action_label");

                    b.ToTable("action_version", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppRole", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_app_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_app_role_code");

                    b.ToTable("app_role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("uq_app_user_login");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.Property<long>("InstructionRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstructionRequestId"));

                    b.Property<long>("ActionVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_version_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("InstructionRequestId")
                        .HasName("pk_instruction_request");

                    b.HasIndex("ActionVersionId")
                        .HasDatabaseName("ix_instruction_request_action_version_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ir_error_created_at_desc")
                        .HasFilter("status = 'ERROR'");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_instruction_request_created_by_user_id");

                    b.HasIndex("ObjectId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ir_object_created_at_desc");

                    b.ToTable("instruction_request", null, t =>
                        {
                            t.HasCheckConstraint("ck_instruction_request_status", "status IN ('DRAFT','CALCULATED','SAVED','ERROR')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.InstructionResult", b =>
                {
                    b.Property<long>("InstructionRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_text");

                    b.HasKey("InstructionRequestId")
                        .HasName("pk_instruction_result");

                    b.ToTable("instruction_result", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Object", b =>
                {
                    b.Property<long>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObjectId"));

                    b.Property<string>("DispatchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispatch_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("ObjectTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_type_id");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.HasKey("ObjectId")
                        .HasName("pk_object");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("uq_object_uid");

                    b.HasIndex("ObjectTypeId", "DispatchName")
                        .IsUnique()
                        .HasDatabaseName("uq_object_type_dispatch_name");

                    b.ToTable("object", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ObjectParamValue", b =>
                {
                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<long>("ParamDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("param_definition_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("numeric")
                        .HasColumnName("value_decimal");

                    b.Property<int?>("ValueIntEnum")
                        .HasColumnType("integer")
                        .HasColumnName("value_int_enum");

                    b.Property<JsonDocument>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("ObjectId", "ParamDefinitionId")
                        .HasName("pk_object_param_value");

                    b.HasIndex("ParamDefinitionId")
                        .HasDatabaseName("ix_object_param_value_param_definition_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_object_param_value_updated_by_user_id");

                    b.ToTable("object_param_value", null, t =>
                        {
                            t.HasCheckConstraint("ck_object_param_value_single_value", "num_nonnulls(value_bool, value_int_enum, value_decimal, value_text, value_json) <= 1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ObjectType", b =>
                {
                    b.Property<long>("ObjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("object_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObjectTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ObjectTypeId")
                        .HasName("pk_object_type");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_object_type_code");

                    b.ToTable("object_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ParamDefinition", b =>
                {
                    b.Property<long>("ParamDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("param_definition_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParamDefinitionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParamDomainId")
                        .HasColumnType("bigint")
                        .HasColumnName("param_domain_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_type");

                    b.HasKey("ParamDefinitionId")
                        .HasName("pk_param_definition");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_param_definition_code");

                    b.HasIndex("ParamDomainId")
                        .HasDatabaseName("ix_param_definition_param_domain_id");

                    b.ToTable("param_definition", null, t =>
                        {
                            t.HasCheckConstraint("ck_param_definition_domain", "((value_type = 'enum' AND param_domain_id IS NOT NULL) OR (value_type <> 'enum' AND param_domain_id IS NULL))");

                            t.HasCheckConstraint("ck_param_definition_value_type", "value_type IN ('bool','enum','int','decimal','text','json')");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ParamDomain", b =>
                {
                    b.Property<long>("ParamDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("param_domain_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ParamDomainId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ParamDomainId")
                        .HasName("pk_param_domain");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_param_domain_code");

                    b.ToTable("param_domain", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ParamDomainValue", b =>
                {
                    b.Property<long>("ParamDomainId")
                        .HasColumnType("bigint")
                        .HasColumnName("param_domain_id");

                    b.Property<int>("ValueCode")
                        .HasColumnType("integer")
                        .HasColumnName("value_code");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_name");

                    b.HasKey("ParamDomainId", "ValueCode")
                        .HasName("pk_param_domain_value");

                    b.HasIndex("ParamDomainId", "ValueName")
                        .IsUnique()
                        .HasDatabaseName("uq_param_domain_value_name");

                    b.ToTable("param_domain_value", null, t =>
                        {
                            t.HasCheckConstraint("ck_param_domain_value_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Entities.RequestParamValue", b =>
                {
                    b.Property<long>("InstructionRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    b.Property<long>("ParamDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("param_definition_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("numeric")
                        .HasColumnName("value_decimal");

                    b.Property<int?>("ValueIntEnum")
                        .HasColumnType("integer")
                        .HasColumnName("value_int_enum");

                    b.Property<JsonDocument>("ValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.Property<string>("ValueOrigin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_origin");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("InstructionRequestId", "ParamDefinitionId")
                        .HasName("pk_request_param_value");

                    b.HasIndex("ParamDefinitionId")
                        .HasDatabaseName("ix_request_param_value_param_definition_id");

                    b.ToTable("request_param_value", null, t =>
                        {
                            t.HasCheckConstraint("ck_request_param_value_origin", "value_origin IN ('CONSTANT_OBJECT','USER_INPUT','SCADA','CALCULATED')");

                            t.HasCheckConstraint("ck_request_param_value_single_value", "num_nonnulls(value_bool, value_int_enum, value_decimal, value_text, value_json) <= 1");
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ActionParamRequirement", b =>
                {
                    b.HasOne("Domain.Entities.ActionVersion", "ActionVersion")
                        .WithMany("ActionParamRequirements")
                        .HasForeignKey("ActionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_action_param_requirement_action_version");

                    b.HasOne("Domain.Entities.ParamDefinition", "ParamDefinition")
                        .WithMany("ActionParamRequirements")
                        .HasForeignKey("ParamDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_action_param_requirement_param_definition");

                    b.Navigation("ActionVersion");

                    b.Navigation("ParamDefinition");
                });

            modelBuilder.Entity("Domain.Entities.ActionVersion", b =>
                {
                    b.HasOne("Domain.Entities.Action", "Action")
                        .WithMany("ActionVersions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_action_version_action");

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.HasOne("Domain.Entities.ActionVersion", "ActionVersion")
                        .WithMany("InstructionRequests")
                        .HasForeignKey("ActionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_action_version");

                    b.HasOne("Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("InstructionRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_created_by");

                    b.HasOne("Domain.Entities.Object", "Object")
                        .WithMany("InstructionRequests")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_object");

                    b.Navigation("ActionVersion");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Domain.Entities.InstructionResult", b =>
                {
                    b.HasOne("Domain.Entities.InstructionRequest", "InstructionRequest")
                        .WithOne("InstructionResult")
                        .HasForeignKey("Domain.Entities.InstructionResult", "InstructionRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_result_request");

                    b.Navigation("InstructionRequest");
                });

            modelBuilder.Entity("Domain.Entities.Object", b =>
                {
                    b.HasOne("Domain.Entities.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_object_object_type");

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("Domain.Entities.ObjectParamValue", b =>
                {
                    b.HasOne("Domain.Entities.Object", "Object")
                        .WithMany("ObjectParamValues")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_object_param_value_object");

                    b.HasOne("Domain.Entities.ParamDefinition", "ParamDefinition")
                        .WithMany("ObjectParamValues")
                        .HasForeignKey("ParamDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_object_param_value_param_definition");

                    b.HasOne("Domain.Entities.AppUser", "UpdatedByUser")
                        .WithMany("ObjectParamValuesUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_object_param_value_updated_by");

                    b.Navigation("Object");

                    b.Navigation("ParamDefinition");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Domain.Entities.ParamDefinition", b =>
                {
                    b.HasOne("Domain.Entities.ParamDomain", "ParamDomain")
                        .WithMany("ParamDefinitions")
                        .HasForeignKey("ParamDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_param_definition_domain");

                    b.Navigation("ParamDomain");
                });

            modelBuilder.Entity("Domain.Entities.ParamDomainValue", b =>
                {
                    b.HasOne("Domain.Entities.ParamDomain", "ParamDomain")
                        .WithMany("ParamDomainValues")
                        .HasForeignKey("ParamDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_param_domain_value_domain");

                    b.Navigation("ParamDomain");
                });

            modelBuilder.Entity("Domain.Entities.RequestParamValue", b =>
                {
                    b.HasOne("Domain.Entities.InstructionRequest", "InstructionRequest")
                        .WithMany("RequestParamValues")
                        .HasForeignKey("InstructionRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_param_value_request");

                    b.HasOne("Domain.Entities.ParamDefinition", "ParamDefinition")
                        .WithMany("RequestParamValues")
                        .HasForeignKey("ParamDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_param_value_param_definition");

                    b.Navigation("InstructionRequest");

                    b.Navigation("ParamDefinition");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role");

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user");

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Domain.Entities.Action", b =>
                {
                    b.Navigation("ActionVersions");
                });

            modelBuilder.Entity("Domain.Entities.ActionVersion", b =>
                {
                    b.Navigation("ActionParamRequirements");

                    b.Navigation("InstructionRequests");
                });

            modelBuilder.Entity("Domain.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("InstructionRequestsCreated");

                    b.Navigation("ObjectParamValuesUpdated");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.Navigation("InstructionResult");

                    b.Navigation("RequestParamValues");
                });

            modelBuilder.Entity("Domain.Entities.Object", b =>
                {
                    b.Navigation("InstructionRequests");

                    b.Navigation("ObjectParamValues");
                });

            modelBuilder.Entity("Domain.Entities.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Domain.Entities.ParamDefinition", b =>
                {
                    b.Navigation("ActionParamRequirements");

                    b.Navigation("ObjectParamValues");

                    b.Navigation("RequestParamValues");
                });

            modelBuilder.Entity("Domain.Entities.ParamDomain", b =>
                {
                    b.Navigation("ParamDefinitions");

                    b.Navigation("ParamDomainValues");
                });
#pragma warning restore 612, 618
        }
    }
}
