// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VkrItDbContext))]
    [Migration("20260125231705_Device_UpaskSwitchTrue_FieldClosingAllowed")]
    partial class Device_UpaskSwitchTrue_FieldClosingAllowed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ActionTable", b =>
                {
                    b.Property<long>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ActionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ActionId")
                        .HasName("pk_action");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppRole", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("pk_app_role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_app_role_code");

                    b.ToTable("app_role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_app_user");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CtPlace", b =>
                {
                    b.Property<long>("CtPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ct_place_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CtPlaceId"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<string>("PlaceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_code");

                    b.HasKey("CtPlaceId")
                        .HasName("pk_ct_place");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_ct_place_device_id");

                    b.ToTable("ct_place", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeviceId"));

                    b.Property<bool>("DzoSwitchTrue")
                        .HasColumnType("boolean")
                        .HasColumnName("dzo_switch_true");

                    b.Property<bool>("FieldClosingAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("field_closing_allowed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<bool>("UpaskSwitchTrue")
                        .HasColumnType("boolean")
                        .HasColumnName("upask_switch_true");

                    b.Property<bool>("VtSwitchTrue")
                        .HasColumnType("boolean")
                        .HasColumnName("vt_switch_true");

                    b.HasKey("DeviceId")
                        .HasName("pk_device");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_device_object_id");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Dfz", b =>
                {
                    b.Property<long>("DfzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dfz_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DfzId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("HazDfz")
                        .HasColumnType("boolean")
                        .HasColumnName("haz_dfz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("DfzId")
                        .HasName("pk_dfz");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_dfz_device_id");

                    b.ToTable("dfz", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Dz", b =>
                {
                    b.Property<long>("DzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dz_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DzId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("HazDz")
                        .HasColumnType("boolean")
                        .HasColumnName("haz_dz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("DzId")
                        .HasName("pk_dz");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_dz_device_id");

                    b.ToTable("dz", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Dzl", b =>
                {
                    b.Property<long>("DzlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dzl_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DzlId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("HazDzl")
                        .HasColumnType("boolean")
                        .HasColumnName("haz_dzl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("DzlId")
                        .HasName("pk_dzl");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_dzl_device_id");

                    b.ToTable("dzl", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.Property<long>("InstructionRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstructionRequestId"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("InstructionRequestId")
                        .HasName("pk_instruction_request");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("ix_instruction_request_action_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_instruction_request_created_by_user_id");

                    b.HasIndex("ObjectId")
                        .HasDatabaseName("ix_instruction_request_object_id");

                    b.ToTable("instruction_request", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InstructionResult", b =>
                {
                    b.Property<long>("InstructionRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_text");

                    b.HasKey("InstructionRequestId")
                        .HasName("pk_instruction_result");

                    b.ToTable("instruction_result", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MtzBusbar", b =>
                {
                    b.Property<long>("MtzBusbarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("mtz_busbar_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MtzBusbarId"));

                    b.Property<bool>("AToBTrue")
                        .HasColumnType("boolean")
                        .HasColumnName("a_to_b_true");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("MtzBusbarId")
                        .HasName("pk_mtz_busbar");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_mtz_busbar_device_id");

                    b.ToTable("mtz_busbar", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Oapv", b =>
                {
                    b.Property<long>("OapvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("oapv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OapvId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<bool>("SwitchOff")
                        .HasColumnType("boolean")
                        .HasColumnName("switch_off");

                    b.HasKey("OapvId")
                        .HasName("pk_oapv");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_oapv_device_id");

                    b.ToTable("oapv", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ObjectTable", b =>
                {
                    b.Property<long>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObjectId"));

                    b.Property<string>("DispatchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispatch_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("ObjectTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_type_id");

                    b.Property<long>("SubstationId")
                        .HasColumnType("bigint")
                        .HasColumnName("substation_id");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.HasKey("ObjectId")
                        .HasName("pk_object");

                    b.HasIndex("ObjectTypeId")
                        .HasDatabaseName("ix_object_object_type_id");

                    b.HasIndex("SubstationId")
                        .HasDatabaseName("ix_object_substation_id");

                    b.ToTable("object", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ObjectType", b =>
                {
                    b.Property<long>("ObjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("object_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ObjectTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ObjectTypeId")
                        .HasName("pk_object_type");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_object_type_code");

                    b.ToTable("object_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RequestParamValue", b =>
                {
                    b.Property<long>("RequestParamValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("request_param_value_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequestParamValueId"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<long?>("DfzId")
                        .HasColumnType("bigint")
                        .HasColumnName("dfz_id");

                    b.Property<long?>("DzId")
                        .HasColumnType("bigint")
                        .HasColumnName("dz_id");

                    b.Property<long?>("DzlId")
                        .HasColumnType("bigint")
                        .HasColumnName("dzl_id");

                    b.Property<long>("InstructionRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("instruction_request_id");

                    b.Property<long?>("MtzBusbarId")
                        .HasColumnType("bigint")
                        .HasColumnName("mtz_busbar_id");

                    b.Property<long?>("OapvId")
                        .HasColumnType("bigint")
                        .HasColumnName("oapv_id");

                    b.Property<long?>("TapvId")
                        .HasColumnType("bigint")
                        .HasColumnName("tapv_id");

                    b.HasKey("RequestParamValueId")
                        .HasName("pk_request_param_value");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_request_param_value_device_id");

                    b.HasIndex("DfzId")
                        .HasDatabaseName("ix_request_param_value_dfz_id");

                    b.HasIndex("DzId")
                        .HasDatabaseName("ix_request_param_value_dz_id");

                    b.HasIndex("DzlId")
                        .HasDatabaseName("ix_request_param_value_dzl_id");

                    b.HasIndex("InstructionRequestId")
                        .HasDatabaseName("ix_request_param_value_instruction_request_id");

                    b.HasIndex("MtzBusbarId")
                        .HasDatabaseName("ix_request_param_value_mtz_busbar_id");

                    b.HasIndex("OapvId")
                        .HasDatabaseName("ix_request_param_value_oapv_id");

                    b.HasIndex("TapvId")
                        .HasDatabaseName("ix_request_param_value_tapv_id");

                    b.ToTable("request_param_value", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Substation", b =>
                {
                    b.Property<long>("SubstationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("substation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubstationId"));

                    b.Property<string>("DispatchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispatch_name");

                    b.HasKey("SubstationId")
                        .HasName("pk_substations");

                    b.ToTable("substations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tapv", b =>
                {
                    b.Property<long>("TapvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tapv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TapvId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<bool>("SwitchOff")
                        .HasColumnType("boolean")
                        .HasColumnName("switch_off");

                    b.HasKey("TapvId")
                        .HasName("pk_tapv");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_tapv_device_id");

                    b.ToTable("tapv", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Vt", b =>
                {
                    b.Property<long>("VtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("vt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VtId"));

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<bool>("Main")
                        .HasColumnType("boolean")
                        .HasColumnName("main");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<string>("PlaceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_code");

                    b.HasKey("VtId")
                        .HasName("pk_vt");

                    b.HasIndex("DeviceId", "Main")
                        .IsUnique()
                        .HasDatabaseName("ix_vt_device_id_main");

                    b.ToTable("vt", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CtPlace", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("CtPlaces")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ct_place_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.HasOne("Domain.Entities.ObjectTable", "Object")
                        .WithMany("Devices")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_object_object_id");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Domain.Entities.Dfz", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Dfzs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dfz_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.Dz", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Dzs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dz_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.Dzl", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Dzls")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dzl_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.HasOne("Domain.Entities.ActionTable", "Action")
                        .WithMany("InstructionRequests")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_action_action_id");

                    b.HasOne("Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("InstructionRequestsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_app_user_created_by_user_id");

                    b.HasOne("Domain.Entities.ObjectTable", "Object")
                        .WithMany("InstructionRequests")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_request_object_object_id");

                    b.Navigation("Action");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Domain.Entities.InstructionResult", b =>
                {
                    b.HasOne("Domain.Entities.InstructionRequest", "InstructionRequest")
                        .WithOne("InstructionResult")
                        .HasForeignKey("Domain.Entities.InstructionResult", "InstructionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_result_instruction_request_instruction_request_");

                    b.Navigation("InstructionRequest");
                });

            modelBuilder.Entity("Domain.Entities.MtzBusbar", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("MtzBusbars")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mtz_busbar_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.Oapv", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Oapvs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oapv_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.ObjectTable", b =>
                {
                    b.HasOne("Domain.Entities.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_object_types_object_type_id");

                    b.HasOne("Domain.Entities.Substation", "Substation")
                        .WithMany("Objects")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_object_substations_substation_id");

                    b.Navigation("ObjectType");

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("Domain.Entities.RequestParamValue", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("RequestParamValues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_param_value_device_device_id");

                    b.HasOne("Domain.Entities.Dfz", "Dfz")
                        .WithMany()
                        .HasForeignKey("DfzId")
                        .HasConstraintName("fk_request_param_value_dfz_dfz_id");

                    b.HasOne("Domain.Entities.Dz", "Dz")
                        .WithMany()
                        .HasForeignKey("DzId")
                        .HasConstraintName("fk_request_param_value_dz_dz_id");

                    b.HasOne("Domain.Entities.Dzl", "Dzl")
                        .WithMany()
                        .HasForeignKey("DzlId")
                        .HasConstraintName("fk_request_param_value_dzl_dzl_id");

                    b.HasOne("Domain.Entities.InstructionRequest", "InstructionRequest")
                        .WithMany("RequestParamValues")
                        .HasForeignKey("InstructionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_param_value_instruction_request_instruction_request");

                    b.HasOne("Domain.Entities.MtzBusbar", "MtzBusbar")
                        .WithMany()
                        .HasForeignKey("MtzBusbarId")
                        .HasConstraintName("fk_request_param_value_mtz_busbar_mtz_busbar_id");

                    b.HasOne("Domain.Entities.Oapv", "Oapv")
                        .WithMany()
                        .HasForeignKey("OapvId")
                        .HasConstraintName("fk_request_param_value_oapv_oapv_id");

                    b.HasOne("Domain.Entities.Tapv", "Tapv")
                        .WithMany()
                        .HasForeignKey("TapvId")
                        .HasConstraintName("fk_request_param_value_tapvs_tapv_id");

                    b.Navigation("Device");

                    b.Navigation("Dfz");

                    b.Navigation("Dz");

                    b.Navigation("Dzl");

                    b.Navigation("InstructionRequest");

                    b.Navigation("MtzBusbar");

                    b.Navigation("Oapv");

                    b.Navigation("Tapv");
                });

            modelBuilder.Entity("Domain.Entities.Tapv", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Tapvs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tapv_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role");

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user");

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Domain.Entities.Vt", b =>
                {
                    b.HasOne("Domain.Entities.Device", "Device")
                        .WithMany("Vts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vt_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Domain.Entities.ActionTable", b =>
                {
                    b.Navigation("InstructionRequests");
                });

            modelBuilder.Entity("Domain.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("InstructionRequestsCreated");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.Navigation("CtPlaces");

                    b.Navigation("Dfzs");

                    b.Navigation("Dzls");

                    b.Navigation("Dzs");

                    b.Navigation("MtzBusbars");

                    b.Navigation("Oapvs");

                    b.Navigation("RequestParamValues");

                    b.Navigation("Tapvs");

                    b.Navigation("Vts");
                });

            modelBuilder.Entity("Domain.Entities.InstructionRequest", b =>
                {
                    b.Navigation("InstructionResult");

                    b.Navigation("RequestParamValues");
                });

            modelBuilder.Entity("Domain.Entities.ObjectTable", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("InstructionRequests");
                });

            modelBuilder.Entity("Domain.Entities.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Domain.Entities.Substation", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
